from django.urls import path
from doctor.views import (
    DoctorReferralListView,
    DoctorCaseDetailView,
    DoctorReviewCreateView,
    DoctorCloseReferralView,
    DoctorMeView,
    DoctorConsultationListView,
    DoctorConsultationDetailView,
    DoctorConsultationScheduleView,
    DoctorConsultationRejectView,
    DoctorConsultationRescheduleView,
    DoctorConsultationCancelView,
    DoctorConsultationCancelView,
    DoctorDashboardStatsView,
    DoctorDirectScheduleView,
    DoctorReviewedCasesView,
)

urlpatterns = [
    path("me/", DoctorMeView.as_view()),
    path("referrals/", DoctorReferralListView.as_view()),
    path("reviewed/", DoctorReviewedCasesView.as_view()),
    path("cases/<uuid:test_id>/", DoctorCaseDetailView.as_view()),
    path("referrals/<int:referral_id>/review/", DoctorReviewCreateView.as_view()),
    path("referrals/<int:referral_id>/close/", DoctorCloseReferralView.as_view()),
    path("consultations/", DoctorConsultationListView.as_view()),
    path("consultations/<int:consultation_id>/", DoctorConsultationDetailView.as_view()),
    path("consultations/<int:consultation_id>/schedule/", DoctorConsultationScheduleView.as_view()),
    path("consultations/create-schedule/", DoctorDirectScheduleView.as_view()),
    path("consultations/<int:consultation_id>/reject/", DoctorConsultationRejectView.as_view()),
    path("consultations/<int:consultation_id>/cancel/", DoctorConsultationCancelView.as_view()),
    path("consultations/<int:consultation_id>/reschedule/", DoctorConsultationRescheduleView.as_view()),
    path("dashboard/stats/", DoctorDashboardStatsView.as_view()),
]
