# Generated by Django 6.0 on 2026-01-04 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('CONFIRM', 'Confirm AI'), ('OVERRIDE', 'Override AI'), ('MORE_TESTS', 'Request More Tests')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctorprofile')),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_review', to='core.referral')),
            ],
        ),
    ]
