# Generated by Django 6.0 on 2026-01-27 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_doctorprofile_availability_timings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='services_offered',
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='current_medications',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lifestyle_indicators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='past_surgeries',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitionerprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='practitionerprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='practitionerprofile',
            name='services_offered',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected'), ('NO_SHOW', 'No Show')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('meet_link', models.CharField(blank=True, max_length=500, null=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='core.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_requests', to='core.patientprofile')),
            ],
        ),
    ]
