# Generated by Django 6.0 on 2026-01-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_patientprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic')], max_length=20),
        ),
    ]
