# Generated by Django 6.0 on 2026-01-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='medical_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
