# Generated by Django 6.0 on 2026-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patientprofile_medical_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostictest',
            name='test_type',
            field=models.CharField(choices=[('TB', 'Tuberculosis Screening'), ('BREAST_CANCER', 'Breast Cancer Screening'), ('DIABETIC_RETINOPATHY', 'Diabetic Retinopathy Check'), ('PNEUMONIA', 'Pneumonia Detection'), ('FRACTURE', 'Hairline Fracture Detection')], max_length=50),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='specialization',
            field=models.CharField(choices=[('TB', 'Tuberculosis'), ('BREAST_CANCER', 'Breast Cancer'), ('DIABETIC_RETINOPATHY', 'Diabetic Retinopathy'), ('PNEUMONIA', 'Pneumonia'), ('FRACTURE', 'Hairline Fracture'), ('GENERAL', 'General Medicine')], max_length=50),
        ),
    ]
